version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: blockstream-satellite_server_1
      APP_PORT: 8080  # Ensure this matches the port used by Blockstream Satellite

  server:
    image: blockstream/satellite:latest
    user: "1000:1000"
    init: true
    volumes:
      - blocksat-cfg:/root/.blocksat/
    devices:
      - /dev/dvb/adapter0:/dev/dvb/adapter0
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    environment:
      - SATELLITE_API_KEY=your_api_key  # Replace with your API key
      - BLOCKSAT_DVB_ADAPTER=/dev/dvb/adapter0

volumes:
  blocksat-cfg:
