version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: zpunks-blockstream-satellite_server_1
      APP_PORT: 8080 

  server:
    image: blockstream/satellite:latest
    user: "1000:1000"
    init: true
    volumes:
      - blocksat-cfg:/root/.blocksat/
    devices:
      - /dev/dvb/adapter0:/dev/dvb/adapter0
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    environment:
      - SATELLITE_API_KEY=your_api_key
      - OTHER_ENV_VAR=value

volumes:
  blocksat-cfg:

