services:
  app_proxy:
    image: your-app-proxy-image:latest  # Replace with the actual image name
    environment:
      APP_HOST: server  # Updated to match the service name
      APP_PORT: 8080

  server:
    image: blockstream/satellite:latest
    user: "1000:1000"
    init: true
    volumes:
      - ~/.bitcoin/:/root/.bitcoin/  # Mount the Bitcoin data directory
      - blocksat-cfg:/root/.blocksat/  # Mount the Blockstream Satellite config
    devices:
      - /dev/dvb/adapter0:/dev/dvb/adapter0
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    environment:
      - SATELLITE_API_KEY=your_api_key  # Replace with your API key
      - BLOCKSAT_DVB_ADAPTER=/dev/dvb/adapter0

volumes:
  blocksat-cfg:
