version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: server  # Updated to match the service name
      APP_PORT: 8080    # Ensure this matches the GUI's port
    depends_on:
      - server          # Ensure the proxy waits for the server to start

  server:
    image: blockstream/satellite:latest
    user: "1000:1000"
    init: true
    volumes:
      - blocksat-cfg:/root/.blocksat/
    devices:
      - /dev/dvb/adapter0:/dev/dvb/adapter0
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    environment:
      - SATELLITE_API_KEY=${SATELLITE_API_KEY}  # Use .env for the API key
      - BLOCKSAT_DVB_ADAPTER=/dev/dvb/adapter0

volumes:
  blocksat-cfg:
